# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPermisos():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_permisos(self):
    self.driver.get("https://pascualbravo.ingejei.com/wp-login.php?redirect_to=https%3A%2F%2Fpascualbravo.ingejei.com%2Fwp-admin%2F&reauth=1")
    self.driver.set_window_size(1015, 755)
    self.driver.find_element(By.ID, "user_login").send_keys("dilan.rodriguez670@pascualbravo.edu.co")
    self.driver.find_element(By.ID, "user_pass").click()
    self.driver.find_element(By.ID, "user_pass").send_keys("z3bNzaFnVTtxt4VVME1(h)57")
    self.driver.find_element(By.ID, "wp-submit").click()
  
