# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://pascualbravo.ingejei.com/wp-admin/user-new.php")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.ID, "user_login").click()
    self.driver.find_element(By.ID, "user_login").send_keys("grupo_5")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("grupo5@gmail.com")
    self.driver.find_element(By.ID, "first_name").click()
    self.driver.find_element(By.ID, "first_name").send_keys("grupo")
    self.driver.find_element(By.ID, "last_name").click()
    self.driver.find_element(By.ID, "last_name").send_keys("5")
    self.driver.find_element(By.ID, "url").click()
    self.driver.find_element(By.ID, "url").send_keys(".")
    dropdown = self.driver.find_element(By.ID, "locale")
    dropdown.find_element(By.XPATH, "//option[. = 'Español de Colombia']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#locale > option:nth-child(3)").click()
    self.driver.find_element(By.ID, "createusersub").click()
  
