# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://pascualbravo.ingejei.com/cart/")
    self.driver.set_window_size(1015, 745)
    self.driver.find_element(By.LINK_TEXT, "Añadir al carrito").click()
    self.driver.execute_script("window.scrollTo(0,56)")
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-quantity-selector__button--plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-item__remove-link").click()
  
