# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://pascualbravo.ingejei.com/cart/")
    self.driver.set_window_size(1015, 748)
    self.driver.find_element(By.LINK_TEXT, "Añadir al carrito").click()
    self.driver.execute_script("window.scrollTo(0,510)")
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart__submit-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-button__text").click()
    dropdown = self.driver.find_element(By.ID, "billing-country")
    dropdown.find_element(By.XPATH, "//option[. = 'Colombia']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(47)").click()
    self.driver.find_element(By.ID, "billing-first_name").click()
    self.driver.find_element(By.ID, "billing-first_name").send_keys("grupo")
    self.driver.find_element(By.ID, "billing-last_name").click()
    self.driver.find_element(By.ID, "billing-last_name").send_keys("5")
    self.driver.find_element(By.ID, "billing-address_1").click()
    self.driver.find_element(By.ID, "billing-address_1").send_keys("123")
    self.driver.find_element(By.ID, "billing-city").click()
    self.driver.find_element(By.ID, "billing-city").send_keys("Medellin")
    self.driver.find_element(By.ID, "billing-state").click()
    dropdown = self.driver.find_element(By.ID, "billing-state")
    dropdown.find_element(By.XPATH, "//option[. = 'Antioquia']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#billing-state > option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-address-form__postcode > label").click()
    self.driver.find_element(By.ID, "billing-postcode").send_keys("050001")
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-checkout-place-order-button__text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-checkout-place-order-button__text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-notice-banner__content > div").click()
  
