# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2PRUEBASFUNCIONALES():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2PRUEBASFUNCIONALES(self):
    self.driver.get("http://localhost:8000/wp-admin/edit.php?post_type=product")
    self.driver.set_window_size(1015, 799)
    self.driver.find_element(By.ID, "post-search-input").send_keys("Maqueta")
    self.driver.find_element(By.ID, "search-submit").click()
  
