# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1PRUEBAFUNCIONAL():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1PRUEBAFUNCIONAL(self):
    self.driver.get("http://localhost:8000/wp-admin/user-new.php")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.ID, "user_login").click()
    self.driver.find_element(By.ID, "user_login").send_keys("usuario1")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("usuario1@gmail.com")
    self.driver.find_element(By.ID, "first_name").click()
    self.driver.find_element(By.ID, "first_name").send_keys("usuario")
    self.driver.find_element(By.ID, "last_name").click()
    self.driver.find_element(By.ID, "last_name").send_keys("1")
    self.driver.find_element(By.ID, "url").click()
    self.driver.find_element(By.ID, "url").send_keys(".")
    dropdown = self.driver.find_element(By.ID, "locale")
    dropdown.find_element(By.XPATH, "//option[. = 'Español de Colombia']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#locale > option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wp-generate-pw").click()
    dropdown = self.driver.find_element(By.ID, "role")
    dropdown.find_element(By.XPATH, "//option[. = 'Cliente']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#role > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "createusersub").click()
  
